### PR TITLE
adds DnD tempate as submodule

### PR DESCRIPTION
**Pull request by matsavage**
Updates latex `TEXINPUTS` environment variable to load DnD template at document compile time

Example to https://github.com/canismarko/dungeon-sheets/issues/92

### CODE REVIEW

**Comment by canismarko** [comment]
Thanks for the PR. I had to make a small modification to make it work, where the TEXINPUTS needed to be ``dungeonsheets/modules/DND-5e-LaTeX-template`` instead of just ``dungeonsheets/modules/``.

**Comment by matsavage** [comment]
Ah that’s interesting. The guide I found suggested that modules// basically meant modules/*/

**Comment by canismarko** [comment]
Yeah it was kind of weird, it worked when I used a regular python venv, but not when I used a conda environment. Not sure if that's why, but it worked this way so I didn't really worry about it any more.

**Comment by matsavage** [comment]
Hahaha after a day of hunting down sheet cantering and latex font paths I’m not going to complain if something just works!

**Comment by bw-mutley** [comment]
hey Mat! Don't worry, I can take it from here. Have fun at your weekend.

**Comment by matsavage** [comment]
Haha don’t worry. This has been long enough coming, I don’t the need for rush now 😂🙂

**Pull request merged**
