### PR TITLE
add feature: portrait images

### PR DESCRIPTION
**Pull request by vincentmalloy**
i added the possibility to add a character portrait to the generated sheet.
the filename must be the same stem as the character.py, extension must be jpeg for now.
i added an example image to the bard1 example

this is the first time i ever tried to contribute to any project, i apologize for any mistakes

### CODE REVIEW

**Comment by canismarko** [comment]
Hi, @vincentmalloy. Thanks for the contribution.

When I try and build the example druid1.py (``makesheets druid1.py``) I get the following error. Mind taking a look?

> Traceback (most recent call last):
  File "/home/mwolf/miniconda3/envs/dungeonsheets/bin/makesheets", line 33, in <module>
    sys.exit(load_entry_point('dungeonsheets', 'console_scripts', 'makesheets')())
  File "/home/mwolf/src/dungeon-sheets/dungeonsheets/make_sheets.py", line 588, in main
    _build(filename, args)
  File "/home/mwolf/src/dungeon-sheets/dungeonsheets/make_sheets.py", line 482, in _build
    make_sheet(
  File "/home/mwolf/src/dungeon-sheets/dungeonsheets/make_sheets.py", line 184, in make_sheet
    ret = make_character_sheet(
  File "/home/mwolf/src/dungeon-sheets/dungeonsheets/make_sheets.py", line 375, in make_character_sheet
    char_pdf = create_character_pdf_template(
TypeError: create_character_pdf_template() got an unexpected keyword argument 'portrait_file'

Also, if you have the time, would you mind adding something to the documentation (maybe in character_sheets.rst) that describes how to use this feature? If not, no worries. I'll open an issue so I can deal with it when I have time.

Cheers.

**Comment by vincentmalloy** [comment]
ok i think i corrected the mixup. i think something is messing with vs code and the linux subsystem that does not let me see changes unless i call git status from the shell. i also really need to look into how to setup python development. so far i am constantly deleting and reinstalling to test my changes.

all files should compute now, they do for me at least. bard1 is the one i added an example picture to.

i will look into updating the docs next

Cheers

**Comment by vincentmalloy** [comment]
i should note that this is somewhat experimental for now. it only works with pdftk and i have not tested it with a variety of image dimensions. i know it does not behave with very large images, i think it converts pixels to pt. im sure it can be made to work with more file formats though.

**Comment by canismarko** [comment]
Merged: https://github.com/canismarko/dungeon-sheets/commit/a1a5d7783adac79114d8b2e49fed8eb00fea77cb

**Pull request closed without merging**
