### PR TITLE
Adding encounter mechanics

### PR DESCRIPTION
**Pull request by stravajiaxen**
It occurred to me that with being able to import characters from other sources, this could be easy to build upon to simulate encounters between a group of `Character`s and a group of `Monster`s. I created an `Agent` class, some `Action` classes and `Event` classes that together store a simulated encounter. I _did_ refactor the existing `Character` and `Monster` classes to extend `Agent`, but it shouldn't change any functionality for character creation.

So far, it's just a very simple PC Ranger vs. Giant Rat mono-et-mono fight in the test_encounter.py module and it doesn't support anything but Attack actions, but it could be extended so long as there were a structure to store Actions, Reactions, etc. available to entities (`Agent`s).

Let me know what you think!

### CODE REVIEW

**Comment by stravajiaxen** [comment]
@canismarko this could be merged whenever, now, though I still consider the feature as a whole a work in progress.

**Comment by canismarko** [comment]
Hey, @stravajiaxen! Thanks for all the work (and extra thanks for including tests). Do you have something specific that you plan to use this feature for? Or if not, what use-cases do you envision this serving? I want to make sure that this is the right way to organize things.

My original goal for dungeonsheets was to be a tool for making character sheets (and maybe monster stat blocks ,etc). Adding the tools for managing encounters would be outside of that scope and I worry it will add extra complexity that I don't have the resources to maintain.

Having said that, I do like the idea of making it so that the various class definitions in dungeonsheets can be easily extended to things like encounters. I want the data model to be as practical as possible and that will help keep the character sheets working well, and also let dungeonsheets serve as a platform for building a separate D&D encounters package. I agree that it makes sense to have ``Monster`` and ``Character`` classes inherit from a common ``Agent`` class.

If there's a good justification why encounters need to be in dungeonsheets, then please let me know. Otherwise, I think I would prefer to include the ``Agent`` base class, but then have the encounter mechanics as a separate package that pulls in dungeonsheets as a requirement.

Thoughts?

**Comment by stravajiaxen** [comment]
@canismarko -- Makes sense to me! This is my first pull request outside of work so I was a little unsure how to best engage with people on it. I decided to just jump right in.

**I'll make a separate module that purely depends on dungeonsheets rather than being part of it.** I can leave the `Agent` class (and if you'd like, the dice utils) so that this new module just leverages those while a separate module depends on that. **I'll just need a little time to modify the commits and start up a separate project.**

For what it's worth, I did this work initially because I had a specific question. I wasn't sure if an encounter that the book said was deadly was _really_ "deadly". For my party of 7 very clever players (!!) the action economy gets all wonk and I don't believe the simple "add some xp numbers, compare to another number and you're good" system anymore. I was trying to see what software was available already to answer my question and dungeon-sheets seemed to be the only module that really had a structure in place to allow you to get into more detail about defining a character so I set out trying to build on it. I'll move the stuff unrelated to the core use of dungeonsheets into another module and continue contributing relevant code to this one.

Thanks! I'll keep you filled in on future updates.

**Comment by geckon** [comment]
Hi guys, FWIW, I also believe it makes sense to have encounters as a separate module, especially if @canismarko doesn't feel he'll have enough energy to maintain it. I'm curious what will come out of it so thumbs up, @stravajiaxen!

As for encounters difficulty there are calculators like this one:
https://kastark.co.uk/rpgs/encounter-calculator-5th/
But they simply use the XP system described in the rules and in my personal experience it's a good simple guidance but it doesn't work too precisely. As a DM I use it to have a basic idea but then I often _fear_ that my encounters will be too easy or too deadly for my players :)

I recently _encountered_ this simulator but I don't have enough experience yet to say how precise it can be:
https://www.dndcombat.com/dndcombat/Welcome.do?section=Fight

**Comment by stravajiaxen** [comment]
Hey @geckon, thanks for sharing those with me. I'm familiar with Kobold Fight Club (http://kobold.club/fight/#/encounter-builder) which has a lot of capabilities but also ultimately just shows you the calculated XP system from the book.

The simulator you recently _encountered_ (heh) also looks really cool! In fact, it looks like where I was envisioning this work would eventually end up. It looks like it considers all the little details I was hoping to eventually also consider (i.e. location, bonus actions vs. regular actions, feats, etc.) I joined the discord they mention on the website and will get in touch with the original author there.

**Comment by stravajiaxen** [comment]
I will close this for now and submit a new pull request later with only the changes regarding the `Agent` class and some typos I saw in the monsters.

**Comment by geckon** [comment]
Let us know if you do end up working on a separate encounter project, I'd be interested :)

**Pull request closed without merging**
