### PR TITLE
Adding the second page of the standard character sheet to the generation (WIP)

### PR DESCRIPTION
**Pull request by Tim-Jackins**
So the standard character sheet [(the one provided by wizards of the coast)](https://media.wizards.com/2016/dnd/downloads/5E_CharacterSheet_Fillable.pdf) includes a page for back story and appearance. I added a function to the build process and a pdf to fill similar to the character sheet that's already in there. I couldn't find contributing info so I hope this PR isn't a problem.

Let me know if you have a question or requests for changes.

For testing, the added fields are:

```python
age = 21
height = '2\'10"'
weight = '38lb'
eyes = 'Brown'
skin = 'White tan'
hair = 'Long and brown'
# Background
allies = ''
faction_name = 'Church of Mask'
backstory = '''
After being brought up by a rogue in the church of mask I am determined to prove myself.
My goal is to become a maskarran in order to attain other worldly powers from serving Mask.
I never new my parents and the only family I have know is my brothers and sisters in the church.
'''
other_feats_traits = ''
treasure = ''
```

P.S.
I love the package and am using it in an upcoming session!

### CODE REVIEW

**Comment by canismarko** [comment]
Thanks, @Tim-Jackins, I'm glad you find it useful.

Thanks for the PR, I'm fine with merging this but I have one request. Would you please add these new attributes to at least one of the example characters (in the ``examples/`` folder). Don't really care which one, just want to make sure it gets tested during CI.

**Comment by canismarko** [comment]
@Tim-Jackins Following up on this PR. Are you able to reconcile this with recent changes and include an example?

**Comment by Tim-Jackins** [comment]
Sorry for the late reply, I'm happy to add an example character. Hoping to do this tonight.

**Comment by Tim-Jackins** [comment]
The possible additions are present in monk1.py.

**Comment by canismarko** [comment]
Great thanks.

**Pull request merged**
