### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by jonbrouse**
This PR adds support to build character sheets with a Docker image. It allows a user to checkout the repository and run `make sheet character=warlock` to build the Docker image and create the player sheet.

### CODE REVIEW

**Comment by TLATER** [comment]
Why not just upload that image to [dockerhub](https://www.docker.com/products/docker-hub)? That way the script could be executed as (say) `docker run canismarko/dungeon-sheets character=warlock`

**Comment by canismarko** [comment]
I've only used docker in a very small way. @TLATER : is your comment something that would keep me from merging this PR?

**Comment by canismarko** [comment]
Also, sorry for the delay in all these PR's, everyone. I didn't get any of the notifications from github for some reason.

**Comment by TLATER** [comment]
@canismarko The MR as-is doesn't follow usual conventions for these things. In fact, typically docker configuration is rarely uploaded into the code repositories.

If you want to change to something a little more standard in the future (happy to help with that if I get some time; I use docker a lot), you'd probably want to regress the workflow suggested in this PR. Whether that is an issue is up to you.

**Comment by jonbrouse** [comment]
The source of my information comes from five years of using Docker as well as images on the Dockerhub with thousands of pulls. I'm going to try and be gentle @TLATER 

> Why not just upload that image to [dockerhub](https://www.docker.com/products/docker-hub)?

Publishing to DockerHub would be a good next step. It could even be automated with new releases. 

>That way the script could be executed as (say) `docker run canismarko/dungeon-sheets character=warlock`

You can run it however you like but your command wouldn't work as it isn't mounting your character file. The docker-compose file and `Makefile` simplify the character sheet build process. 

> @canismarko The MR as-is doesn't follow usual conventions for these things. 

I think you may want to reconsider what you're basing your conventions on. It definitely follows best practices and conventions.

>In fact, typically docker configuration is rarely uploaded into the code repositories.

Are the Dockerfiles that build your images not in version control? If you build an image with your code inside of it, you are going to put the Dockerfile in version control. Also, Dockerhub can't automatiaclly build your image nor ensure the Dockerfile you claim built your image is actually what built it. 

> If you want to change to something a little more standard in the future (happy to help with that if I get some time; I use docker a lot), you'd probably want to regress the workflow suggested in this PR. Whether that is an issue is up to you.

If you're interested in working on this and learning more about how to use Docker in production and within software companies I'd be willing to help you out.

**Comment by TLATER** [comment]
@jonbrouse I have similar amounts of experience and you don't seem to make any real criticism of my comment there. We may both want to reconsider conventions and conversation tone. I probably wrote that annoyed at how annoying it was to execute this, apologies @canismarko.

I could spend some time reviewing and actually considering a PR, but there hasn't been any movement on this in almost a year, so I'm not sure there's any point, nor do I understand why you'd restart the conversation like that, outside of the chance of humbling me a bit.

**Comment by jonbrouse** [comment]
Honestly, I haven't thought about this project since that last PR. @canismarko if you don't want to leverage Docker in your project, I totally understand. I would, however, caution against seriously considering input from contributors who have not reviewed the PR.

**Comment by Valentin-Metz** [comment]
@canismarko https://github.com/canismarko/dungeon-sheets/pull/156 should implement all of this.

As to what https://github.com/canismarko/dungeon-sheets/pull/156 does differently compared to this PR:
1. We don't call a makefile, but call the python script directly
2. We don't publish a docker-compose, instead
3. Releases are automatically built and published by GitHub actions  (since 2019 GitHub has implemented their own container repository, so no outside account setup is necessary)

**Pull request closed without merging**
