### PR TITLE
Removed non utf-8 characters

### PR DESCRIPTION
**Pull request by Tim-Jackins**
I kept running into the build error that there weren't understandable characters so I went (grep sed-ed) through and replace the non utf-8 character with valid characters. Let me know if there are any changes I should make. Thanks!

### CODE REVIEW

**Comment by pbatroff** [comment]
I just saw this PR - created one as well for basically the same problem. (see #33). Hopefully both PRs will get merged

**Comment by geckon** [comment]
It would be great if @canismarko found time to merge fixes that are done and ready so that we're not fixing these issues separately in our forks.

How do you guys @Tim-Jackins @pbatroff use your forks? Do you just build and install packages locally? Do you sync your forks with each other's?

**Comment by pbatroff** [comment]
> How do you guys @Tim-Jackins @pbatroff use your forks? Do you just build and install packages locally? Do you sync your forks with each other's?

I have my own fork, where I manage the PR - I think this is default procedure. I made a branch for that issue and just work in that branch.

**Comment by canismarko** [comment]
Oh wow! I didn't realize these PR's were piling up. So sorry everyone. I will get working on the back-log soon.

On a side note, any idea how to get github to send me an e-mail when a repo I own (but not all the other repos I'm watching) gets a pull request?

**Comment by pbatroff** [comment]
It should do that automatically - check your notification settings here, and verify the correct email! ;) I got a mail from just participating in this thread!

**Comment by geckon** [comment]
@canismarko Thanks a lot for merging these! Unfortunately I don't really know how to set this. I think there is an option for separate settings per organizations but not sure about individual repositories, sorry.

**Comment by geckon** [comment]
@canismarko From a quick google search it seems that GitHub only allows you to set "participating" and "watching" notifications separately which is I suppose what you did:
https://help.github.com/en/github/managing-subscriptions-and-notifications-on-github/configuring-notifications#about-participating-and-watching-notifications

And now you would like to set it to receive only emails for those watching notifications that are related to a repo you own, right?

That doesn't seem to be possible unfortunately. GitHub instead recommends to set up filtering in your email client:
https://help.github.com/en/github/managing-subscriptions-and-notifications-on-github/configuring-notifications#customizing-your-email-notifications

What I can personally do is to mark your github handle in my PRs and you should get an email for these but that doesn't scale very well...

**Comment by canismarko** [comment]
Thanks @geckon, that's the same conclusion I came to. I used to have e-mail notifications turned on, but I got way to much chatter from repos I was watching. I did discover that I can mark other repos as "Watch releases", so that may cut down on the noise enough.

If not, I'll check out the filtering thing you mentioned.

**Pull request merged**
