### PR TITLE
Render half-caster spell sheets, cleanup existing spell sheet generation

### PR DESCRIPTION
**Pull request by meson800**
For half-casters like warlocks and paladins, all of the available spells do not fit on the current spell sheet that is generated. However, if we could use the half-caster sheet in these cases (which stops at spell level 5), we could show all of the spells. In other cases, it may be preferred to show all available spells on multiple pages. Luckily, @agrgordon sat down and made PDF-fillable versions of the official half-caster sheet. 

This PR adds/modifies the following:
1. Simplifies the PDF field labeling on the full- and half-caster sheets. Instead of the fields being named weird field numbers, the spell name fields are now uniformly named `Spells 1xii` (e.g. the 5th fourth-level spell is `Spells 1504`). The prepared checkbox is named `prepared xii`. This greatly simplifies the field assignment, as we don't need lookup tables anymore.
2. If the character has only fifth-level spells and lower _and_ their spell list would not fit on the full-caster sheet, this generates and uses the half-caster sheet template.
3. If the character still exceeds the spell limit (crazy multiclassing?), this **generates extra spell pages** to contain the overflow spells. This is the speculative part of the PR; do you want this behavior, or the old behavior of just showing the prepared spells in this case?

### CODE REVIEW

**Comment by meson800** [comment]
(something [funky](https://github.com/actions/setup-python/issues/544) looks like it happened with the `setup-python` action and Python 3.6, added a commit to fix it)

**Comment by meson800** [comment]
Example of what the new half-caster sheet looks like:
half_caster_example

**Comment by canismarko** [comment]
Thanks @meson800. Since the tests seem previously broken, I need to take some time and clean everything up, so I will make sure the examples build properly when I do that.

**Comment by meson800** [comment]
I can add a cleaned-up example in a new PR. The given one is from an actual campaign sheet.

**Comment by canismarko** [comment]
Much appreciated!

**Pull request merged**
