### PR TITLE
Major additions including Multiclassing, Features, VOLO/EE races, and SCAG backgrounds

### PR DESCRIPTION
**Pull request by bacook17**
Hey there,

This package is absolutely incredible. I've been looking for something like it for a SUPER long time. Thank you so much for developing it!

This pull request includes a bunch of (relatively large) changes. The most significant is allowing for multiclassing. This requires changing a Character object from being subclassed by a Class to it being a standalone object with a list of Classes, each with their own level. I've put the new implementation through some pretty rigorous tests, and I think it should be bug-free, but famous last words. I've also tried to keep backwards compatability for loading old "*.py" files, since the new version requires a new format.

The other major changes include:

- Added new races from VOLO and Elemental Evil Player's Companion
- Added new backgrounds from Sword Coast Adventurer's Guide
- Some bug fixes (ex: proficiency wasn't being added to Animal Handling or Sleight of Hand because of spaces in their names)
- A preliminary attempt at a "Features" class, similar to your "Spells" class. All races and backgrounds now have a list of Features associated with them. Short names are added automatically to the "Features and Traits" section of the Character Sheet, and it generates a PDF with full descriptions, just like with spells. There's major work still to be done in adding features for all classes and (eventually) subclasses.

Thank you so much again for creating this project. I'm super excited to help with developing it.

### CODE REVIEW

**Comment by jonbrouse** [comment]
@bacook17 have you had a chance to take a look at the [failing tests in Travis build](https://travis-ci.com/canismarko/dungeon-sheets/jobs/166618432)?

**Comment by bacook17** [comment]
Hey Jonathon,

I actually wasn't aware of those tests, sorry! That's helpful, I'll try to
make sure I've run them through those test suites better.

Ive corrected that bug and made some other additions, but I'm away from my
computer at the moment. I'll run some tests before I add to the PR.

Thanks for bringing this to my attention!

Be

**Comment by bacook17** [comment]
Hey there,

I've updated so that all the tests pass except for a small error related to druid spells, which is a distinct implementation choice I'd like to change. While I understand that as written, druids don't have "spells known" vs "spells prepared" (just a set of spells ), I think it makes the whole process easier to assume all character have "spells" and "spells prepared" (with all spells prepared included in spells) and have users keep track of whether their class has "unprepared" spells.

So, all that said, I'd like to ask if it's appropriate for me to change / update the tests included if I want to change the implementation of the code. For instance, the change in how druid spells work, but I also  had to put in a number of hackey additions to make the code backwards compatible. Is it preferable to force the code to be backwards compatible or rewrite the tests to make them compatible with a new implementation?

Thanks for your thoughts.
Ben

**Comment by jonbrouse** [comment]
@bacook17 sorry, I'm not the maintainer

**Comment by canismarko** [comment]
Thanks so much for all this work. Apparently github wasn't notifying me of new pull requests, so sorry for the delay. I'm going to take a look at this one closer to see what's in it. I'm really intrigued about multiclassing. That's something I've wanted to add for a while but hadn't found a great way to do it.

**Comment by bacook17** [comment]
Thanks Mark, and thank you for your awesome work in developing this
package. Hopefully everything should be fairly straightforward, but I have
yet to add good tests for the new additions.

**Comment by canismarko** [comment]
Hi, @bacook17. Thanks so much for all this effort! It really looks like you put in a lot of work. I merged your PR in manually since there were a few conflicts. We should be good to go.

**Pull request merged**
