### PR TITLE
Add all SRD Monsters

### LINKED ISSUE #85: Add support for climbing speed
Speed, swimming speed and flying speed are all supported by `monsters.py`. It would be nice to have also climbing speed there.

### PR DESCRIPTION
**Pull request by stravajiaxen**
Also fixes #85 . I added all the monsters available through the SRD using an autogenerated script. I also autogenerated the tests, though they only check for whether the monsters can be created.

I noticed that, besides `Ankylosaurus`, all of the other creatures were already in the SRD. Is `Ankylosaurus` not an SRD monster? It might be worth removing it so that the monsters file could be entirely autogenerated (oh, and the copyright, too...)

The autogenerating code is available through https://github.com/stravajiaxen/5e-srd-to-py.

### CODE REVIEW

**Comment by stravajiaxen** [comment]
Of note, this pull request is huge -- but it's also very repetitive.

**Comment by stravajiaxen** [comment]
Is it worth refactoring this first into multiple files, similar to the spells?

**Comment by canismarko** [comment]
Wow, perfect timing. I just added the ability to make a list of monsters for GM notes and happened to notice this PR while I was searching for a script to automate adding monsters. Like, this PR showed up as the first hit on my google results...

Anyway, thanks for this.

**Comment by stravajiaxen** [comment]
Haha, that's too funny! I've written a python script to generate python code maybe 3 times (including this one) and I always feel like a wizard when doing it.

**Pull request merged**
