### PR TITLE
Entity Class + Typo Fixes

### PR DESCRIPTION
**Pull request by stravajiaxen**
From the discussion about an encounter mechanic, refactored pull request 94 (https://github.com/canismarko/dungeon-sheets/pull/94) to just do the `Entity` class. I changed the name, too -- `Actor` was specific about actions.

I also found some typos in the `Monster` class (amazingly it's always spelled "passive Perception" in the books with that capitalization for instance). Also fixed a bug in `dungeonsheets.stats.Skill` for the `RemarkableAthlete` feat (`proficiency_bonus` was spelled wrong -- apparently the test suites never used it?)

I plan to put the other work I had been doing in `Encounter` into a separate module that depends on `dungeonsheets`.

### CODE REVIEW

**Comment by stravajiaxen** [comment]
Ah, broke some stuff in `character.py`. Fixing it up then will be ready for review. Looks like there's more that may need to be moved into `entity.py`

**Comment by stravajiaxen** [comment]
@canismarko ready whenever! Let me know if you want any changes.

**Comment by canismarko** [comment]
Thanks, @stravajiaxen!

**Comment by stravajiaxen** [comment]
I'm off hiking in the Adirondacks this weekend. Will publish some initial work based off this architecture soon and "@" you and @geckon when it's up.

Oh, I also saw a nice .csv in a similar project that could be parsed to turn into a bunch of new monster classes. Might do a bit of that, just to do something simple and self-contained https://github.com/matteoferla/DnD-battler/blob/master/DnD_battler/beastiary.csv

**Pull request merged**
